[build-system]
requires = ["setuptools", "wheel", "Cython"]
build-backend = "setuptools.build_meta"

[tool.black]
exclude = "^env/"
line-length = 100

[tool.isort]
profile = "black" # needed for black/isort compatibility
line_length = 100
