language: c

sudo: false

compiler:
  - gcc
  - clang

cache:
  directories:
    - $HOME/local
    - $HOME/.luarocks
    - $HOME/.ccache
    - $HOME/.local

addons:
  apt:
    sources:
    packages:
      - lua5.1
      - liblua5.1-0-dev
      - luarocks
      - uuid-dev
      - aspell
      - libopenmpi-dev
      - ccache
      - libhwloc-dev
      - libmunge-dev
      - munge

before_install:
  - export LD_LIBRARY_PATH=$HOME/local/lib
  - export CPPFLAGS=-I$HOME/local/include
  - export LDFLAGS=-L$HOME/local/lib
  - export PKG_CONFIG_PATH=$HOME/local2/lib/pkgconfig:$HOME/local/lib/pkgconfig
  - export BUILDDIR=$HOME/local2/build
  - test "$TRAVIS_PULL_REQUEST" == "false" || export CCACHE_READONLY=1
  - if test "$CC" = "clang"; then export CCACHE_CPP2=1; fi
  - eval `luarocks path`
  - wget https://raw.githubusercontent.com/flux-framework/flux-core/master/src/test/travis-dep-builder.sh
  - bash ./travis-dep-builder.sh --cachedir=$HOME/local/.cache
  - bash ./travis-dep-builder.sh --printenv
  - pip install --user cffi coverage

script:
 - export CC="ccache $CC"
 - git clone https://github.com/flux-framework/flux-core.git $HOME/flux-core
 - (cd $HOME/flux-core && mkdir -p $BUILDDIR && cp -r * $BUILDDIR)
 - (cd $HOME/flux-core && ./autogen.sh && ./configure --prefix=$HOME/local2 && make -j 2 && make install)
 - (rm -fr $HOME/flux-core)
 - ($HOME/local2/bin/flux keygen)
 - autoreconf -i && ./configure --with-flux-core-builddir=$BUILDDIR && make check

after_failure:
 - find . -name t[0-9]*.output -print0 | xargs -0 -I'{}' sh -c 'printf "\033[31mFound {}\033[39m\n";cat {}'
 - find . -name *.broker.log -print0 | xargs -0 -I'{}' sh -c 'printf "\033[31mFound {}\033[39m\n";cat {}'

